"""Added clothes model

Revision ID: 268146b5ffe9
Revises: 
Create Date: 2021-07-13 12:18:39.292802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '268146b5ffe9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clothes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('cloth_type', sa.String(), nullable=False),
    sa.Column('temp_tag', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('rain', sa.Boolean(), nullable=False),
    sa.Column('sun', sa.Boolean(), nullable=False),
    sa.Column('icon_path', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clothes')
    # ### end Alembic commands ###
