"""Fixed clothes model

Revision ID: 754bbd942dea
Revises: 
Create Date: 2021-07-14 12:18:04.752583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '754bbd942dea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clothes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('cloth_type', sa.String(), nullable=False),
    sa.Column('temp_freezing', sa.Boolean(), nullable=False),
    sa.Column('temp_cold', sa.Boolean(), nullable=False),
    sa.Column('temp_chilly', sa.Boolean(), nullable=False),
    sa.Column('temp_warm', sa.Boolean(), nullable=False),
    sa.Column('temp_hot', sa.Boolean(), nullable=False),
    sa.Column('rain', sa.Boolean(), nullable=False),
    sa.Column('sun', sa.Boolean(), nullable=False),
    sa.Column('icon_path', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clothes')
    # ### end Alembic commands ###
